zenfone3: Update blobs from asus WW_15.0410.1803.53
Signed-off-by: Planet-X <planetx.dev@gmail.com>

diff --git a/proprietary/vendor/bin/hostapd_cmd b/proprietary/vendor/bin/hostapd_cmd
--- a/proprietary/vendor/bin/hostapd_cmd
+++ b/proprietary/vendor/bin/hostapd_cmd
@@ -11,6 +11,27 @@ ACTION=`getprop persist.sys.wifi.hostapd.cmd`
 
 log -t $LOG_TAG -p d hostapd_cmd enter
 
+retry_connect=10
+while [ $retry_connect -ne 0 ];
+do
+	hostapd_cli -iwlan0 -p/data/misc/wifi/hostapd/ctrl interface
+	ret1=$?
+
+	log -t $LOG_TAG -p d "ret1=$ret1"
+	if [ $ret1 -eq 0 ]; then
+		log -t $LOG_TAG -p d "hostapd connectable"
+		break
+	else
+		retry_connect=`expr $retry_connect - 1`
+		log -t $LOG_TAG -p d "hostapd not connectable, retrying... ($retry_connect)"
+		usleep 100000
+	fi
+done
+if [ $retry_connect -eq 0 ]; then
+	log -t $LOG_TAG -p d "ERROR: cannot connect to hostapd!"
+	exit -1
+fi
+
 if [ "$ACTION" = "add_reload" -o "$ACTION" = "remove_reload" ]
 then
 hostapd_cli -p/data/misc/wifi/hostapd/ctrl -iwlan0 set macaddr_acl 1
